# Generated by Django 2.2.4 on 2019-09-05 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Renda Mensal')),
                ('current_score', models.IntegerField(default=974, verbose_name='Pontuação Atual')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.CharField(max_length=50, verbose_name='Limite de Crédito')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_card.Client', verbose_name='Cliente')),
            ],
        ),
    ]
